/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
	/*
	@Test

	void appHasAGreeting() {
		Datenbankmodifications classUnderTest = new Datenbankmodifications();
		try {
			assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
		} catch (Exception e) {
			fail();
		}
	}*/

	@Test
	void testTest(){
		assertEquals(1, 1);
	}


}
