/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;
import javafx.scene.text.Text;
import javafx.stage.Stage;


public class App extends Application {
	  @Override
	    public void start(Stage stage) {
		  	//Setup
		  double[] difference = {0} ;
		  	try {
				difference[0] = new Datenbankmodifications().sum();
			} catch (Exception e) {
			}
		  	String diff = difference[0] + "";
		  	Button eingaben = new Button("Transaktion hinzuf\u00fcgen");
		  	Button aktualisieren = new Button("Aktualisieren");
		  	// Umlaute werden sonst nicht richtig dargestellt
		  	stage.setTitle("F\u00dcFA");
	        Text text = new Text("F\u00dcFA - Finanz \u00dcbersicht f\u00fcr Anf\u00e4nger");
	        Label differenz = new Label("Aktuelle Differenz:");
	        Label space = new Label(diff);
	        BorderPane border = new BorderPane();
	        VBox leftborder = new VBox(10);
	        HBox bottomborder = new HBox(20);
	        String[] dates = {" "};
	        try {
				 dates = new Datenbankmodifications().datesWithDetails();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	        ListView<String> listView = new ListView<>();
	        ObservableList<String> items = FXCollections.observableArrayList(
                   dates[0], dates[1],dates[2], dates[3],dates[4], dates[5],
                   dates[6], dates[7],dates[8], dates[9]
            );
	        listView.setItems(items);
	        bottomborder.getChildren().addAll(eingaben);
	        border.setRight(aktualisieren);
	        leftborder.getChildren().addAll( differenz, space );
	        text.setFill(Color.BLACK);
	        text.setFont(Font.font("Comic Sans MS", FontPosture.ITALIC, 20));
	        border.setTop(new StackPane(text));
	        border.setBottom(bottomborder);
	        border.setLeft(leftborder);
	        border.setCenter(listView);
	        
	        //Eingaben von Ein-und Ausgaben realisieren
	        
	        eingaben.setOnAction(e -> Eingaben.display());
	        aktualisieren.setOnAction(e->{ 
	        	try {
	        		String neu = "";
					difference[0] = new Datenbankmodifications().sum();
					neu = difference[0] + "";
					space.setText(neu);
				} catch (Exception e1) {
				}
	        });
	        Scene scene = new Scene(border, 640, 480);
	        stage.setScene(scene);
	        stage.show();
	    }

	public static void main(String[] args) throws Exception {
		launch();
		new Datenbankmodifications().getGreeting();
	}
}
